# Generated by Django 4.0.1 on 2023-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('buy_date', models.DateField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
