# Generated by Django 4.1.4 on 2023-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfaq',
            name='Idd',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
