# Generated by Django 4.0.1 on 2023-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatfaq_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfaq',
            name='type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
