# Generated by Django 4.2.2 on 2023-07-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatfaq_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatfaq',
            name='type',
        ),
    ]
