# Generated by Django 4.2.3 on 2023-07-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_trial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
