# Generated by Django 4.2.3 on 2023-07-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='Idd',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
