# Generated by Django 4.1.4 on 2023-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pro_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
