# Generated by Django 4.1.4 on 2023-05-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_registration_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_login',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
