# Generated by Django 4.2.2 on 2023-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
